name: Build, test and deploy LedgerWallet

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build_install:
    name: Build and install the Ledgerblue Python package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Setup Python version
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Build & install
      run: |
        pip install -U pip
        pip install -U .

  deploy:
    name: Build and deploy ledgerblue package
    needs: build_install
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_pypi_deployment.yml@main
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    with:
      package_name: ledgerblue
      jfrog_deployment: true
      release: true
      publish: true
    secrets:
      pypi_token: ${{ secrets.PYPI_PUBLIC_API_TOKEN }}
